using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CustomClientValidation.Models
{
    public class Customer
    {
        public int ID { get; set; } //will be auto generated by DB

        //Username should not contain special characters
        [RegularExpression("^[a-zA-Z0-9 ]+$")]
        public string Username { get; set; }

        //Remote attribute to check to see if the email exists in DB
        [Required(ErrorMessage ="Please enter an email address")]
        [Display(Name = "Email Address")]
        [Remote("CheckEmail","Validation")]
        public string EmailAddress { get; set; } = string.Empty;

        //Minimum age of 18
        [MinimumAge(18, ErrorMessage = "You must be at least 18 years old")]
        [Required(ErrorMessage ="Please enter a date of birth")]
        [Display(Name = "Date of Birth")]
        
        public DateTime? DOB { get; set; }

        [Required(ErrorMessage ="Please enter a password")]
        [Compare("ConfirmPassword")]
        [StringLength(25,ErrorMessage ="Please limit your password to 25 characters")]
        public string Password { get; set; } = string.Empty;

        [Required(ErrorMessage ="Please confirm your password")]
        [Display(Name = "Confirm Password")]
        [NotMapped]
        public string ConfirmPassword { get; set; } = string.Empty;
    }
}
